# Generated by Django 4.0.3 on 2022-05-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_pictures_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='photo',
            field=models.ImageField(blank=True, height_field='367', null=True, upload_to='products', width_field='440'),
        ),
    ]
