# Generated by Django 4.0.3 on 2022-05-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_pictures_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='photo',
            new_name='rasm',
        ),
    ]
