# Generated by Django 4.0.3 on 2022-05-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_photo_pictures_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='rasm',
            field=models.ImageField(default=1, upload_to='products'),
            preserve_default=False,
        ),
    ]
