# Generated by Django 4.0.3 on 2022-05-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
